enum Actions {
	SET_AR = 'SET_AR',
	SET_EN = 'SET_EN',
	REVIEW_SERVICE = 'REVIEW_SERVICE',
	REPORT_ISSUE = 'REPORT_ISSUE',
	SHARE_LOCATION = 'SHARE_LOCATION',
	START = 'START',
	NEXT = 'NEXT',
	RATING = 'RATING',
	RATING_BAD = 'RATING_BAD',
	RATING_GOOD = 'RATING_GOOD',
	RATING_EXCELLENT = 'RATING_EXCELLENT',
}
export default Actions
